version: '3'

services:
  mongo:
    image: mongo:4
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: demo
      MONGO_INITDB_ROOT_PASSWORD: demo

  mongo-express:
    image: mongo-express:0.49.0
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 4002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: demo
      ME_CONFIG_MONGODB_ADMINPASSWORD: demo

  demo-app:
    build:
      context: ./DemoApp
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 4000:80
